[serv]
Customer=PERTO
DeviceName=QY
DeviceModel=
DevicePort=/dev/ttyS5
DeviceBaudrate=9600
DeviceParity=NONE
DeviceDataBits=8
DeviceStopBit=1
DeviceTxTimeout=1000
DeviceRxTimeout=5000
DeviceFlowControl=NONE
DeviceProtocol=Perto485
PhysicalLayer=SERIAL
NumberOFLeds=6
EnableSoundControl=N
LogPath=/Zanthus/Zeus/lib_u64/log/
LogName=siu_F00TN000.log
LogGenerate=Y
LogLevel=INI|FIM|WRN|ERR|INF|STA|DBX|CFG|DBG
;CONFIGURACAO PARA SELF CHECKOUT FIRMWARE F00TN000

;LED_BLUE

[serv.PERTO_SIU_INDICATOR_LED_ORANGE]
command_position=3

[serv.PERTO_SIU_INDICATOR_LED_GREEN]  
command_position=4

[serv.PERTO_SIU_INDICATOR_LED_RED]  
command_position=5


; /********** END [ serv ] ****************/





